apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: dencel2/cart-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: RabbitMq-UserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitMq-Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: Authentication-Key
          valueFrom:
            secretKeyRef:
              name: authentication-key
              key: signing-key
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080