apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-user
  template:
    metadata:
      labels:
        app: mssql-user
    spec:
      containers:
      - name: mssql-user
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-connection
              key: Password
        volumeMounts:
        - name: mssqldb-user
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mssqldb-user
        persistentVolumeClaim:
          claimName: mssql-user-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-user-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: mssql-user
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-user-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: mssql-user
  ports:
    - protocol: TCP
      port: 1533
      targetPort: 1433