apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: dencel2/user-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: UserServiceConnection
          valueFrom:
            secretKeyRef:
              name: user-service-connection
              key: ConnectionString
        - name: Authentication-Key
          valueFrom:
            secretKeyRef:
              name: authentication-key
              key: signing-key
        - name: RabbitMq-UserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitMq-Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 666
      targetPort: 666