apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - name: port-1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port-2
      protocol: TCP
      port: 8081
      targetPort: 8081
