apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: dencel2/auth-service:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: AuthServiceConnection
          valueFrom:
            secretKeyRef:
              name: auth-service-connection
              key: ConnectionString
        - name: RabbitMqUserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitMqPassword
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: AuthenticationToken
          valueFrom:
            secretKeyRef:
              name: authentication-key
              key: signing-key
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080