apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-product
  template:
    metadata:
      labels:
        app: mssql-product
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql/data"]
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql/data
      containers:
      - name: mssql-product
        image: mcr.microsoft.com/mssql/server:2019-latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-service-connection
              key: Password
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-product-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: mssql-product
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-product-loadbalancer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: mssql-product
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433